// flow-typed signature: fdc8ae4383e78bc91ba841a21391ca6b
// flow-typed version: <<STUB>>/@types/react_v~16.9.35/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
