// flow-typed signature: 9e5c85ced435c7e1ec998a5b67ab82a1
// flow-typed version: <<STUB>>/@types/react-native_v~0.63.2/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-native' {
  declare module.exports: any;
}
