// flow-typed signature: e178651626d218283743bd44db03616e
// flow-typed version: <<STUB>>/expo-clipboard_v^1.0.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-clipboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-clipboard/build/Clipboard' {
  declare module.exports: any;
}

declare module 'expo-clipboard/build/ExpoClipboard' {
  declare module.exports: any;
}

declare module 'expo-clipboard/build/ExpoClipboard.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-clipboard/build/Clipboard.js' {
  declare module.exports: $Exports<'expo-clipboard/build/Clipboard'>;
}
declare module 'expo-clipboard/build/ExpoClipboard.js' {
  declare module.exports: $Exports<'expo-clipboard/build/ExpoClipboard'>;
}
declare module 'expo-clipboard/build/ExpoClipboard.web.js' {
  declare module.exports: $Exports<'expo-clipboard/build/ExpoClipboard.web'>;
}
