// flow-typed signature: f3125b92fd5fb76465118a1ede0d1046
// flow-typed version: <<STUB>>/expo-image-picker_v~9.2.0/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-image-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-image-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-image-picker/build/ExponentImagePicker' {
  declare module.exports: any;
}

declare module 'expo-image-picker/build/ExponentImagePicker.web' {
  declare module.exports: any;
}

declare module 'expo-image-picker/build/ImagePicker' {
  declare module.exports: any;
}

declare module 'expo-image-picker/build/ImagePicker.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-image-picker/build/ExponentImagePicker.js' {
  declare module.exports: $Exports<'expo-image-picker/build/ExponentImagePicker'>;
}
declare module 'expo-image-picker/build/ExponentImagePicker.web.js' {
  declare module.exports: $Exports<'expo-image-picker/build/ExponentImagePicker.web'>;
}
declare module 'expo-image-picker/build/ImagePicker.js' {
  declare module.exports: $Exports<'expo-image-picker/build/ImagePicker'>;
}
declare module 'expo-image-picker/build/ImagePicker.types.js' {
  declare module.exports: $Exports<'expo-image-picker/build/ImagePicker.types'>;
}
