// flow-typed signature: 39888fb4fae10e51cadb54ea4215251a
// flow-typed version: <<STUB>>/expo-location_v~10.0.0/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-location'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-location' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-location/build/ExpoLocation' {
  declare module.exports: any;
}

declare module 'expo-location/build/ExpoLocation.web' {
  declare module.exports: any;
}

declare module 'expo-location/build/GeolocationPolyfill' {
  declare module.exports: any;
}

declare module 'expo-location/build/Location' {
  declare module.exports: any;
}

declare module 'expo-location/build/Location.types' {
  declare module.exports: any;
}

declare module 'expo-location/build/LocationEventEmitter' {
  declare module.exports: any;
}

declare module 'expo-location/build/LocationEventEmitter.web' {
  declare module.exports: any;
}

declare module 'expo-location/build/LocationGoogleGeocoding' {
  declare module.exports: any;
}

declare module 'expo-location/build/LocationSubscribers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-location/build/ExpoLocation.js' {
  declare module.exports: $Exports<'expo-location/build/ExpoLocation'>;
}
declare module 'expo-location/build/ExpoLocation.web.js' {
  declare module.exports: $Exports<'expo-location/build/ExpoLocation.web'>;
}
declare module 'expo-location/build/GeolocationPolyfill.js' {
  declare module.exports: $Exports<'expo-location/build/GeolocationPolyfill'>;
}
declare module 'expo-location/build/Location.js' {
  declare module.exports: $Exports<'expo-location/build/Location'>;
}
declare module 'expo-location/build/Location.types.js' {
  declare module.exports: $Exports<'expo-location/build/Location.types'>;
}
declare module 'expo-location/build/LocationEventEmitter.js' {
  declare module.exports: $Exports<'expo-location/build/LocationEventEmitter'>;
}
declare module 'expo-location/build/LocationEventEmitter.web.js' {
  declare module.exports: $Exports<'expo-location/build/LocationEventEmitter.web'>;
}
declare module 'expo-location/build/LocationGoogleGeocoding.js' {
  declare module.exports: $Exports<'expo-location/build/LocationGoogleGeocoding'>;
}
declare module 'expo-location/build/LocationSubscribers.js' {
  declare module.exports: $Exports<'expo-location/build/LocationSubscribers'>;
}
