// flow-typed signature: c24b6ebc8e2335702b78030f08bad735
// flow-typed version: <<STUB>>/radio-buttons-react-native_v^1.0.4/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'radio-buttons-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'radio-buttons-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'radio-buttons-react-native/RadioButtonRN' {
  declare module.exports: any;
}

// Filename aliases
declare module 'radio-buttons-react-native/RadioButtonRN.js' {
  declare module.exports: $Exports<'radio-buttons-react-native/RadioButtonRN'>;
}
