// flow-typed signature: 1c24fca494f125908d00a3f03d6a14a5
// flow-typed version: <<STUB>>/react-native-range-slider-expo_v^1.3.7/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-range-slider-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-range-slider-expo' {
  declare module.exports: any;
}
