// flow-typed signature: 0885911d8da638b8bf591e85b6ec597d
// flow-typed version: <<STUB>>/react-native-map-link_v^2.7.20/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-map-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-map-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-map-link/src/components/Popup' {
  declare module.exports: any;
}

declare module 'react-native-map-link/src/constants' {
  declare module.exports: any;
}

declare module 'react-native-map-link/src' {
  declare module.exports: any;
}

declare module 'react-native-map-link/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-map-link/index' {
  declare module.exports: $Exports<'react-native-map-link'>;
}
declare module 'react-native-map-link/index.js' {
  declare module.exports: $Exports<'react-native-map-link'>;
}
declare module 'react-native-map-link/src/components/Popup.js' {
  declare module.exports: $Exports<'react-native-map-link/src/components/Popup'>;
}
declare module 'react-native-map-link/src/constants.js' {
  declare module.exports: $Exports<'react-native-map-link/src/constants'>;
}
declare module 'react-native-map-link/src/index' {
  declare module.exports: $Exports<'react-native-map-link/src'>;
}
declare module 'react-native-map-link/src/index.js' {
  declare module.exports: $Exports<'react-native-map-link/src'>;
}
declare module 'react-native-map-link/src/utils.js' {
  declare module.exports: $Exports<'react-native-map-link/src/utils'>;
}
