// flow-typed signature: 4faa68721690a7044f8c81c78a866f9f
// flow-typed version: <<STUB>>/react-native-communications_v^2.2.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-communications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-communications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-communications/AKCommunications' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-communications/AKCommunications.js' {
  declare module.exports: $Exports<'react-native-communications/AKCommunications'>;
}
