// flow-typed signature: e9a5f25bfceb9ee8f6b18b123adc6509
// flow-typed version: <<STUB>>/react-native-circle-checkbox_v^0.1.6/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-circle-checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-circle-checkbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-circle-checkbox/index' {
  declare module.exports: $Exports<'react-native-circle-checkbox'>;
}
declare module 'react-native-circle-checkbox/index.js' {
  declare module.exports: $Exports<'react-native-circle-checkbox'>;
}
