// flow-typed signature: d4963ca9bdd3afecf5f74841b96738f9
// flow-typed version: <<STUB>>/react-native-cached-image_v^1.4.3/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cached-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cached-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-cached-image/CachedImage' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/ImageCacheManager' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/ImageCacheManagerOptionsPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/ImageCachePreloader' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/ImageCacheProvider' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/utils/fsUtils' {
  declare module.exports: any;
}

declare module 'react-native-cached-image/utils/pathUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-cached-image/CachedImage.js' {
  declare module.exports: $Exports<'react-native-cached-image/CachedImage'>;
}
declare module 'react-native-cached-image/ImageCacheManager.js' {
  declare module.exports: $Exports<'react-native-cached-image/ImageCacheManager'>;
}
declare module 'react-native-cached-image/ImageCacheManagerOptionsPropTypes.js' {
  declare module.exports: $Exports<'react-native-cached-image/ImageCacheManagerOptionsPropTypes'>;
}
declare module 'react-native-cached-image/ImageCachePreloader.js' {
  declare module.exports: $Exports<'react-native-cached-image/ImageCachePreloader'>;
}
declare module 'react-native-cached-image/ImageCacheProvider.js' {
  declare module.exports: $Exports<'react-native-cached-image/ImageCacheProvider'>;
}
declare module 'react-native-cached-image/index' {
  declare module.exports: $Exports<'react-native-cached-image'>;
}
declare module 'react-native-cached-image/index.js' {
  declare module.exports: $Exports<'react-native-cached-image'>;
}
declare module 'react-native-cached-image/utils/fsUtils.js' {
  declare module.exports: $Exports<'react-native-cached-image/utils/fsUtils'>;
}
declare module 'react-native-cached-image/utils/pathUtils.js' {
  declare module.exports: $Exports<'react-native-cached-image/utils/pathUtils'>;
}
