// flow-typed signature: d25c44d64c61e67dce82b6b929490762
// flow-typed version: <<STUB>>/yarnpkg_v^0.15.1/flow_v0.154.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarnpkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarnpkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yarnpkg/bin/yarn' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/api' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/aliases' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/_build-sub-commands' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/_execute-lifecycle-script' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/_useless' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/access' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/add' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/bin' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/cache' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/check' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/clean' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/config' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/fieri' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/generate-lock-entry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/global' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/info' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/init' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/install' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/licenses' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/link' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/login' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/logout' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/ls' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/outdated' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/owner' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/pack' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/publish' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/remove' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/run' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/self-update' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/tag' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/team' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/unlink' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/upgrade' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/version' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli/commands/why' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/cli' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/config' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/constants' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/errors' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/fetchers/base-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/fetchers/copy-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/fetchers/git-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/fetchers' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/fetchers/tarball-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/lockfile/parse' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/lockfile/stringify' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/lockfile/wrapper' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-compatibility' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-constraint-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-hoister' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-install-scripts' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-linker' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-reference' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-request' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/package-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/registries/base-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/registries/bower-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/registries' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/registries/npm-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/registries/yarn-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/base-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/buffer-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/console/console-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/console/progress-bar' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/console/spinner-progress' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/console/util' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/event-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/format' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/json-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/lang/en' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/lang' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/reporters/types' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/base-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/bitbucket-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/exotic-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/file-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/gist-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/git-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/github-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/gitlab-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/hosted-git-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/registry-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/exotics/tarball-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/registries/bower-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/registries/npm-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/registries/registry-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/resolvers/registries/yarn-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/types' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/blocking-queue' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/child' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/crypto' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/execute-lifecycle-script' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/filter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/fs' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/git' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/map' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/misc' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/network' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest/fix' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest/infer-license' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest/licenses' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest/typos' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest/util' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/normalize-manifest/validate' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/parse-package-name' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/promise' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/request-manager' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/stream' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib-legacy/util/version' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/api' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/aliases' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/_build-sub-commands' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/_execute-lifecycle-script' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/_useless' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/access' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/add' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/bin' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/cache' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/check' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/clean' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/config' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/fieri' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/generate-lock-entry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/global' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/info' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/init' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/install' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/licenses' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/link' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/login' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/logout' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/ls' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/outdated' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/owner' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/pack' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/publish' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/remove' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/run' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/self-update' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/tag' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/team' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/unlink' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/upgrade' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/version' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli/commands/why' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/cli' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/config' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/constants' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/errors' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/fetchers/base-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/fetchers/copy-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/fetchers/git-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/fetchers' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/fetchers/tarball-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/lockfile/parse' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/lockfile/stringify' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/lockfile/wrapper' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-compatibility' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-constraint-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-fetcher' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-hoister' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-install-scripts' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-linker' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-reference' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-request' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/package-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/registries/base-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/registries/bower-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/registries' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/registries/npm-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/registries/yarn-registry' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/base-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/buffer-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/console/console-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/console/progress-bar' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/console/spinner-progress' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/console/util' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/event-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/format' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/json-reporter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/lang/en' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/lang' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/reporters/types' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/base-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/bitbucket-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/exotic-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/file-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/gist-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/git-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/github-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/gitlab-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/hosted-git-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/registry-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/exotics/tarball-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/registries/bower-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/registries/npm-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/registries/registry-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/resolvers/registries/yarn-resolver' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/types' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/blocking-queue' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/child' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/crypto' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/execute-lifecycle-script' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/filter' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/fs' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/git' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/map' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/misc' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/network' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest/fix' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest/infer-license' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest/licenses' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest/typos' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest/util' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/normalize-manifest/validate' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/parse-package-name' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/promise' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/request-manager' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/stream' {
  declare module.exports: any;
}

declare module 'yarnpkg/lib/util/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yarnpkg/bin/yarn.js' {
  declare module.exports: $Exports<'yarnpkg/bin/yarn'>;
}
declare module 'yarnpkg/lib-legacy/api.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/api'>;
}
declare module 'yarnpkg/lib-legacy/cli/aliases.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/aliases'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/_build-sub-commands.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/_build-sub-commands'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/_execute-lifecycle-script.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/_execute-lifecycle-script'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/_useless.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/_useless'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/access.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/access'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/add.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/add'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/bin.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/bin'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/cache.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/cache'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/check.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/check'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/clean.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/clean'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/config.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/config'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/fieri.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/fieri'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/generate-lock-entry.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/generate-lock-entry'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/global.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/global'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/info.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/info'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/init.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/init'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/install.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/install'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/licenses.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/licenses'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/link.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/link'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/login.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/login'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/logout.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/logout'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/ls.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/ls'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/outdated.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/outdated'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/owner.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/owner'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/pack.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/pack'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/publish.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/publish'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/remove.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/remove'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/run.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/run'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/self-update.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/self-update'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/tag.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/tag'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/team.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/team'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/unlink.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/unlink'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/upgrade.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/upgrade'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/version.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/version'>;
}
declare module 'yarnpkg/lib-legacy/cli/commands/why.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli/commands/why'>;
}
declare module 'yarnpkg/lib-legacy/cli/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli'>;
}
declare module 'yarnpkg/lib-legacy/cli/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/cli'>;
}
declare module 'yarnpkg/lib-legacy/config.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/config'>;
}
declare module 'yarnpkg/lib-legacy/constants.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/constants'>;
}
declare module 'yarnpkg/lib-legacy/errors.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/errors'>;
}
declare module 'yarnpkg/lib-legacy/fetchers/base-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/fetchers/base-fetcher'>;
}
declare module 'yarnpkg/lib-legacy/fetchers/copy-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/fetchers/copy-fetcher'>;
}
declare module 'yarnpkg/lib-legacy/fetchers/git-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/fetchers/git-fetcher'>;
}
declare module 'yarnpkg/lib-legacy/fetchers/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/fetchers'>;
}
declare module 'yarnpkg/lib-legacy/fetchers/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/fetchers'>;
}
declare module 'yarnpkg/lib-legacy/fetchers/tarball-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/fetchers/tarball-fetcher'>;
}
declare module 'yarnpkg/lib-legacy/lockfile/parse.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/lockfile/parse'>;
}
declare module 'yarnpkg/lib-legacy/lockfile/stringify.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/lockfile/stringify'>;
}
declare module 'yarnpkg/lib-legacy/lockfile/wrapper.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/lockfile/wrapper'>;
}
declare module 'yarnpkg/lib-legacy/package-compatibility.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-compatibility'>;
}
declare module 'yarnpkg/lib-legacy/package-constraint-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-constraint-resolver'>;
}
declare module 'yarnpkg/lib-legacy/package-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-fetcher'>;
}
declare module 'yarnpkg/lib-legacy/package-hoister.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-hoister'>;
}
declare module 'yarnpkg/lib-legacy/package-install-scripts.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-install-scripts'>;
}
declare module 'yarnpkg/lib-legacy/package-linker.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-linker'>;
}
declare module 'yarnpkg/lib-legacy/package-reference.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-reference'>;
}
declare module 'yarnpkg/lib-legacy/package-request.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-request'>;
}
declare module 'yarnpkg/lib-legacy/package-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/package-resolver'>;
}
declare module 'yarnpkg/lib-legacy/registries/base-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/registries/base-registry'>;
}
declare module 'yarnpkg/lib-legacy/registries/bower-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/registries/bower-registry'>;
}
declare module 'yarnpkg/lib-legacy/registries/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/registries'>;
}
declare module 'yarnpkg/lib-legacy/registries/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/registries'>;
}
declare module 'yarnpkg/lib-legacy/registries/npm-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/registries/npm-registry'>;
}
declare module 'yarnpkg/lib-legacy/registries/yarn-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/registries/yarn-registry'>;
}
declare module 'yarnpkg/lib-legacy/reporters/base-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/base-reporter'>;
}
declare module 'yarnpkg/lib-legacy/reporters/buffer-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/buffer-reporter'>;
}
declare module 'yarnpkg/lib-legacy/reporters/console/console-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/console/console-reporter'>;
}
declare module 'yarnpkg/lib-legacy/reporters/console/progress-bar.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/console/progress-bar'>;
}
declare module 'yarnpkg/lib-legacy/reporters/console/spinner-progress.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/console/spinner-progress'>;
}
declare module 'yarnpkg/lib-legacy/reporters/console/util.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/console/util'>;
}
declare module 'yarnpkg/lib-legacy/reporters/event-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/event-reporter'>;
}
declare module 'yarnpkg/lib-legacy/reporters/format.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/format'>;
}
declare module 'yarnpkg/lib-legacy/reporters/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters'>;
}
declare module 'yarnpkg/lib-legacy/reporters/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters'>;
}
declare module 'yarnpkg/lib-legacy/reporters/json-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/json-reporter'>;
}
declare module 'yarnpkg/lib-legacy/reporters/lang/en.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/lang/en'>;
}
declare module 'yarnpkg/lib-legacy/reporters/lang/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/lang'>;
}
declare module 'yarnpkg/lib-legacy/reporters/lang/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/lang'>;
}
declare module 'yarnpkg/lib-legacy/reporters/types.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/reporters/types'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/base-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/base-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/bitbucket-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/bitbucket-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/exotic-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/exotic-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/file-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/file-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/gist-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/gist-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/git-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/git-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/github-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/github-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/gitlab-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/gitlab-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/hosted-git-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/hosted-git-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/registry-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/registry-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/exotics/tarball-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/exotics/tarball-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/registries/bower-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/registries/bower-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/registries/npm-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/registries/npm-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/registries/registry-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/registries/registry-resolver'>;
}
declare module 'yarnpkg/lib-legacy/resolvers/registries/yarn-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/resolvers/registries/yarn-resolver'>;
}
declare module 'yarnpkg/lib-legacy/types.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/types'>;
}
declare module 'yarnpkg/lib-legacy/util/blocking-queue.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/blocking-queue'>;
}
declare module 'yarnpkg/lib-legacy/util/child.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/child'>;
}
declare module 'yarnpkg/lib-legacy/util/crypto.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/crypto'>;
}
declare module 'yarnpkg/lib-legacy/util/execute-lifecycle-script.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/execute-lifecycle-script'>;
}
declare module 'yarnpkg/lib-legacy/util/filter.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/filter'>;
}
declare module 'yarnpkg/lib-legacy/util/fs.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/fs'>;
}
declare module 'yarnpkg/lib-legacy/util/git.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/git'>;
}
declare module 'yarnpkg/lib-legacy/util/map.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/map'>;
}
declare module 'yarnpkg/lib-legacy/util/misc.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/misc'>;
}
declare module 'yarnpkg/lib-legacy/util/network.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/network'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/fix.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest/fix'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/index' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/infer-license.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest/infer-license'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/licenses.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest/licenses'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/typos.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest/typos'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/util.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest/util'>;
}
declare module 'yarnpkg/lib-legacy/util/normalize-manifest/validate.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/normalize-manifest/validate'>;
}
declare module 'yarnpkg/lib-legacy/util/parse-package-name.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/parse-package-name'>;
}
declare module 'yarnpkg/lib-legacy/util/promise.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/promise'>;
}
declare module 'yarnpkg/lib-legacy/util/request-manager.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/request-manager'>;
}
declare module 'yarnpkg/lib-legacy/util/stream.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/stream'>;
}
declare module 'yarnpkg/lib-legacy/util/version.js' {
  declare module.exports: $Exports<'yarnpkg/lib-legacy/util/version'>;
}
declare module 'yarnpkg/lib/api.js' {
  declare module.exports: $Exports<'yarnpkg/lib/api'>;
}
declare module 'yarnpkg/lib/cli/aliases.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/aliases'>;
}
declare module 'yarnpkg/lib/cli/commands/_build-sub-commands.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/_build-sub-commands'>;
}
declare module 'yarnpkg/lib/cli/commands/_execute-lifecycle-script.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/_execute-lifecycle-script'>;
}
declare module 'yarnpkg/lib/cli/commands/_useless.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/_useless'>;
}
declare module 'yarnpkg/lib/cli/commands/access.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/access'>;
}
declare module 'yarnpkg/lib/cli/commands/add.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/add'>;
}
declare module 'yarnpkg/lib/cli/commands/bin.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/bin'>;
}
declare module 'yarnpkg/lib/cli/commands/cache.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/cache'>;
}
declare module 'yarnpkg/lib/cli/commands/check.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/check'>;
}
declare module 'yarnpkg/lib/cli/commands/clean.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/clean'>;
}
declare module 'yarnpkg/lib/cli/commands/config.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/config'>;
}
declare module 'yarnpkg/lib/cli/commands/fieri.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/fieri'>;
}
declare module 'yarnpkg/lib/cli/commands/generate-lock-entry.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/generate-lock-entry'>;
}
declare module 'yarnpkg/lib/cli/commands/global.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/global'>;
}
declare module 'yarnpkg/lib/cli/commands/index' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands'>;
}
declare module 'yarnpkg/lib/cli/commands/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands'>;
}
declare module 'yarnpkg/lib/cli/commands/info.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/info'>;
}
declare module 'yarnpkg/lib/cli/commands/init.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/init'>;
}
declare module 'yarnpkg/lib/cli/commands/install.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/install'>;
}
declare module 'yarnpkg/lib/cli/commands/licenses.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/licenses'>;
}
declare module 'yarnpkg/lib/cli/commands/link.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/link'>;
}
declare module 'yarnpkg/lib/cli/commands/login.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/login'>;
}
declare module 'yarnpkg/lib/cli/commands/logout.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/logout'>;
}
declare module 'yarnpkg/lib/cli/commands/ls.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/ls'>;
}
declare module 'yarnpkg/lib/cli/commands/outdated.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/outdated'>;
}
declare module 'yarnpkg/lib/cli/commands/owner.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/owner'>;
}
declare module 'yarnpkg/lib/cli/commands/pack.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/pack'>;
}
declare module 'yarnpkg/lib/cli/commands/publish.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/publish'>;
}
declare module 'yarnpkg/lib/cli/commands/remove.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/remove'>;
}
declare module 'yarnpkg/lib/cli/commands/run.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/run'>;
}
declare module 'yarnpkg/lib/cli/commands/self-update.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/self-update'>;
}
declare module 'yarnpkg/lib/cli/commands/tag.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/tag'>;
}
declare module 'yarnpkg/lib/cli/commands/team.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/team'>;
}
declare module 'yarnpkg/lib/cli/commands/unlink.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/unlink'>;
}
declare module 'yarnpkg/lib/cli/commands/upgrade.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/upgrade'>;
}
declare module 'yarnpkg/lib/cli/commands/version.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/version'>;
}
declare module 'yarnpkg/lib/cli/commands/why.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli/commands/why'>;
}
declare module 'yarnpkg/lib/cli/index' {
  declare module.exports: $Exports<'yarnpkg/lib/cli'>;
}
declare module 'yarnpkg/lib/cli/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/cli'>;
}
declare module 'yarnpkg/lib/config.js' {
  declare module.exports: $Exports<'yarnpkg/lib/config'>;
}
declare module 'yarnpkg/lib/constants.js' {
  declare module.exports: $Exports<'yarnpkg/lib/constants'>;
}
declare module 'yarnpkg/lib/errors.js' {
  declare module.exports: $Exports<'yarnpkg/lib/errors'>;
}
declare module 'yarnpkg/lib/fetchers/base-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib/fetchers/base-fetcher'>;
}
declare module 'yarnpkg/lib/fetchers/copy-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib/fetchers/copy-fetcher'>;
}
declare module 'yarnpkg/lib/fetchers/git-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib/fetchers/git-fetcher'>;
}
declare module 'yarnpkg/lib/fetchers/index' {
  declare module.exports: $Exports<'yarnpkg/lib/fetchers'>;
}
declare module 'yarnpkg/lib/fetchers/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/fetchers'>;
}
declare module 'yarnpkg/lib/fetchers/tarball-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib/fetchers/tarball-fetcher'>;
}
declare module 'yarnpkg/lib/lockfile/parse.js' {
  declare module.exports: $Exports<'yarnpkg/lib/lockfile/parse'>;
}
declare module 'yarnpkg/lib/lockfile/stringify.js' {
  declare module.exports: $Exports<'yarnpkg/lib/lockfile/stringify'>;
}
declare module 'yarnpkg/lib/lockfile/wrapper.js' {
  declare module.exports: $Exports<'yarnpkg/lib/lockfile/wrapper'>;
}
declare module 'yarnpkg/lib/package-compatibility.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-compatibility'>;
}
declare module 'yarnpkg/lib/package-constraint-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-constraint-resolver'>;
}
declare module 'yarnpkg/lib/package-fetcher.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-fetcher'>;
}
declare module 'yarnpkg/lib/package-hoister.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-hoister'>;
}
declare module 'yarnpkg/lib/package-install-scripts.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-install-scripts'>;
}
declare module 'yarnpkg/lib/package-linker.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-linker'>;
}
declare module 'yarnpkg/lib/package-reference.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-reference'>;
}
declare module 'yarnpkg/lib/package-request.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-request'>;
}
declare module 'yarnpkg/lib/package-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/package-resolver'>;
}
declare module 'yarnpkg/lib/registries/base-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib/registries/base-registry'>;
}
declare module 'yarnpkg/lib/registries/bower-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib/registries/bower-registry'>;
}
declare module 'yarnpkg/lib/registries/index' {
  declare module.exports: $Exports<'yarnpkg/lib/registries'>;
}
declare module 'yarnpkg/lib/registries/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/registries'>;
}
declare module 'yarnpkg/lib/registries/npm-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib/registries/npm-registry'>;
}
declare module 'yarnpkg/lib/registries/yarn-registry.js' {
  declare module.exports: $Exports<'yarnpkg/lib/registries/yarn-registry'>;
}
declare module 'yarnpkg/lib/reporters/base-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/base-reporter'>;
}
declare module 'yarnpkg/lib/reporters/buffer-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/buffer-reporter'>;
}
declare module 'yarnpkg/lib/reporters/console/console-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/console/console-reporter'>;
}
declare module 'yarnpkg/lib/reporters/console/progress-bar.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/console/progress-bar'>;
}
declare module 'yarnpkg/lib/reporters/console/spinner-progress.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/console/spinner-progress'>;
}
declare module 'yarnpkg/lib/reporters/console/util.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/console/util'>;
}
declare module 'yarnpkg/lib/reporters/event-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/event-reporter'>;
}
declare module 'yarnpkg/lib/reporters/format.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/format'>;
}
declare module 'yarnpkg/lib/reporters/index' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters'>;
}
declare module 'yarnpkg/lib/reporters/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters'>;
}
declare module 'yarnpkg/lib/reporters/json-reporter.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/json-reporter'>;
}
declare module 'yarnpkg/lib/reporters/lang/en.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/lang/en'>;
}
declare module 'yarnpkg/lib/reporters/lang/index' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/lang'>;
}
declare module 'yarnpkg/lib/reporters/lang/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/lang'>;
}
declare module 'yarnpkg/lib/reporters/types.js' {
  declare module.exports: $Exports<'yarnpkg/lib/reporters/types'>;
}
declare module 'yarnpkg/lib/resolvers/base-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/base-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/bitbucket-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/bitbucket-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/exotic-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/exotic-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/file-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/file-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/gist-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/gist-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/git-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/git-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/github-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/github-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/gitlab-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/gitlab-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/hosted-git-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/hosted-git-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/registry-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/registry-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/exotics/tarball-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/exotics/tarball-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/index' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers'>;
}
declare module 'yarnpkg/lib/resolvers/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers'>;
}
declare module 'yarnpkg/lib/resolvers/registries/bower-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/registries/bower-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/registries/npm-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/registries/npm-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/registries/registry-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/registries/registry-resolver'>;
}
declare module 'yarnpkg/lib/resolvers/registries/yarn-resolver.js' {
  declare module.exports: $Exports<'yarnpkg/lib/resolvers/registries/yarn-resolver'>;
}
declare module 'yarnpkg/lib/types.js' {
  declare module.exports: $Exports<'yarnpkg/lib/types'>;
}
declare module 'yarnpkg/lib/util/blocking-queue.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/blocking-queue'>;
}
declare module 'yarnpkg/lib/util/child.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/child'>;
}
declare module 'yarnpkg/lib/util/crypto.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/crypto'>;
}
declare module 'yarnpkg/lib/util/execute-lifecycle-script.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/execute-lifecycle-script'>;
}
declare module 'yarnpkg/lib/util/filter.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/filter'>;
}
declare module 'yarnpkg/lib/util/fs.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/fs'>;
}
declare module 'yarnpkg/lib/util/git.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/git'>;
}
declare module 'yarnpkg/lib/util/map.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/map'>;
}
declare module 'yarnpkg/lib/util/misc.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/misc'>;
}
declare module 'yarnpkg/lib/util/network.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/network'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/fix.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest/fix'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/index' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/index.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/infer-license.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest/infer-license'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/licenses.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest/licenses'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/typos.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest/typos'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/util.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest/util'>;
}
declare module 'yarnpkg/lib/util/normalize-manifest/validate.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/normalize-manifest/validate'>;
}
declare module 'yarnpkg/lib/util/parse-package-name.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/parse-package-name'>;
}
declare module 'yarnpkg/lib/util/promise.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/promise'>;
}
declare module 'yarnpkg/lib/util/request-manager.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/request-manager'>;
}
declare module 'yarnpkg/lib/util/stream.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/stream'>;
}
declare module 'yarnpkg/lib/util/version.js' {
  declare module.exports: $Exports<'yarnpkg/lib/util/version'>;
}
